import type { Metadata } from "next";
import type { CSSProperties } from "react";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { blogConfig } from "@/blog.config";
import { getPost, getPosts, getTranslationManifest, type Authorship } from "@/lib/posts";
import { formatDate } from "@/lib/format";
import { Markdown, MarkdownSlot } from "@/components/markdown";
import { parseMarkdown, splitContentSlots } from "@/lib/markdown";
import { Icon } from "@/components/icon";
import { ArticleTools } from "@/components/article-tools";
import { ArticleImage } from "@/components/article-image";
import { ReadingProgress } from "@/components/reading-navigation";

import { localePath, categoryLabel, tagLabel, languageTag, type Locale } from "@/lib/i18n";
import { metadataAlternates } from "@/lib/metadata";

const authorshipLabels: Record<Locale, Record<Authorship, string>> = {
  zh: {
    "human-only": "作者独立创作",
    "human-ai-polished": "作者创作 · AI 辅助润色",
    "ai-human-reviewed": "AI 起草 · 作者审阅",
    "ai-only": "AI 生成",
  },
  en: {
    "human-only": "Written by the author",
    "human-ai-polished": "Written by the author · Polished with AI",
    "ai-human-reviewed": "Drafted with AI · Reviewed by the author",
    "ai-only": "Generated by AI",
  },
  ja: {
    "human-only": "著者による執筆",
    "human-ai-polished": "著者が執筆 · AI による推敲",
    "ai-human-reviewed": "AI が起草 · 著者が確認",
    "ai-only": "AI による生成",
  },
};

export function postMetadata(slug: string, locale: Locale): Metadata {
  const post = getPost(slug, undefined, locale);
  if (!post) notFound();
  return {
    title: post.seoTitle || post.title,
    description: post.seoDescription || post.description,
    keywords: post.tags,
    alternates: metadataAlternates(locale, getTranslationManifest()[localePath(`/posts/${post.slug}`, locale)]),
    openGraph: {
      type: "article",
      title: post.seoTitle || post.title,
      description: post.seoDescription || post.description,
      publishedTime: post.published || post.date,
      modifiedTime: post.updated,
      section: (post.categories || [post.category]).join(" / "),
      tags: post.tags,
      authors: [blogConfig.author],
      url: localePath(`/posts/${post.slug}`, locale),
      locale: { zh: "zh_CN", en: "en_US", ja: "ja_JP" }[locale],
      images: post.cover ? [{ url: post.cover, alt: post.title }] : [],
    },
  };
}

export default function PostPage({ slug, locale = "zh" }: { slug: string; locale?: Locale }) {
  const post = getPost(slug, undefined, locale);
  if (!post) notFound();
  const contentSlots = splitContentSlots(parseMarkdown(post.content)).slots;
  const posts = getPosts(undefined, locale);
  const index = posts.findIndex((item) => item.slug === post.slug);
  const neighbors = [
    { post: posts[index + 1], label: { zh: "上一篇", en: "Previous post", ja: "前の記事" }[locale] },
    { post: posts[index - 1], label: { zh: "下一篇", en: "Next post", ja: "次の記事" }[locale] },
  ].filter((item) => item.post);
  const permalink = new URL(localePath(`/posts/${post.slug}`, locale), blogConfig.url).href;
  const publicationDate = post.published || post.date;
  const license = post.license || blogConfig.technical.contentLicense;
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    headline: post.title,
    description: post.seoDescription || post.description,
    datePublished: publicationDate,
    dateModified: post.updated,
    articleSection: post.categories || [post.category],
    keywords: post.tags,
    license: post.licenseUrl,
    inLanguage: languageTag(locale),
    image: post.cover ? new URL(post.cover, blogConfig.url).href : undefined,
    author: { "@type": "Person", name: blogConfig.author },
    mainEntityOfPage: new URL(localePath(`/posts/${post.slug}`, locale), blogConfig.url).href,
  };
  return (
    <>
      <article className={`article-page article-${post.type}`} id="article-top">
        <ReadingProgress />
        <header
          className={`reading-header${post.cover ? " has-cover" : ""}`}
          style={{ "--reading-cover-filter": post.coverFilter || (post.coverDim ? "brightness(0.75)" : undefined) } as CSSProperties}
        >
          {post.cover && (
            <ArticleImage
              key={post.cover}
              variant="cover"
              src={post.cover}
              objectPosition={post.coverPosition}
              alt={post.title}
            />
          )}
          <div className="reading-header-nav">
            {!post.hideInfo && <div className="reading-meta">
              <Link href={localePath("/about", locale)} aria-label={`${{ zh: "作者", en: "Author", ja: "著者" }[locale]} ${blogConfig.author}`}>{blogConfig.author}</Link>
              <span title={formatDate(publicationDate.slice(0, 10), true, locale)}>
                <Icon name="pencil" />
                <time dateTime={publicationDate}>{formatDate(publicationDate.slice(0, 10), false, locale)}</time>
              </span>
              {post.updated && (
                <span title={formatDate(post.updated.slice(0, 10), true, locale)}>
                  {{ zh: "更新于", en: "Updated", ja: "更新" }[locale]} <time dateTime={post.updated}>{formatDate(post.updated.slice(0, 10), false, locale)}</time>
                </span>
              )}
              <span className="reading-category-path">
                <Link className="category-label" data-category={post.category} href={localePath(`/?category=${encodeURIComponent(post.category)}`, locale)}>
                  <Icon name={post.category === "技术" ? "tool" : "folder"} />
                  {categoryLabel(post.category, locale)}
                </Link>
                {post.categories?.slice(1).map(category => <span key={category}> / {categoryLabel(category, locale)}</span>)}
              </span>
              <span><Icon name="pilcrow" />{post.wordCount.toLocaleString(languageTag(locale))} {{ zh: "字", en: "words", ja: "文字" }[locale]}</span>
            </div>}
            <ArticleTools
              title={`【${blogConfig.title}】${post.title}`}
              description={post.description}
              url={permalink}
            />
          </div>
          <h1 className="reading-title">{post.title}</h1>
        </header>
        {post.description && (
          <p className="reading-description"><Icon name="sparkle" />{post.description}</p>
        )}
        <div id="article-body" className={`prose reading-prose md-${post.type}`}>
          <Markdown content={post.content} />
        </div>
        <footer className="reading-footer">
          <div className="reading-tags">
            {post.tags.map((tag) => (
              <Link href={localePath(`/?tag=${encodeURIComponent(tag)}`, locale)} key={tag}>#{tagLabel(tag, locale)}</Link>
            ))}
          </div>
          {!!post.references?.length && (
            <section className="reading-attribution reading-references" aria-label={{ zh: "参考链接", en: "References", ja: "参考リンク" }[locale]}>
              <h2>{{ zh: "参考链接", en: "References", ja: "参考リンク" }[locale]}</h2>
              <ul>
                {post.references.map((reference, referenceIndex) => (
                  <li key={referenceIndex}>
                    {reference.link
                      ? <a href={reference.link} target={/^https?:/.test(reference.link) ? "_blank" : undefined} rel="noopener noreferrer">{reference.title || reference.link}</a>
                      : reference.title}
                  </li>
                ))}
              </ul>
            </section>
          )}
          <div className="reading-attribution">
            <Link href={localePath("/about", locale)} className="reading-author">
              <Image src={blogConfig.avatar} alt="" width={44} height={44} />
              <span><strong>{blogConfig.author}</strong></span>
            </Link>
            {post.authorship && <p className="reading-authorship">{authorshipLabels[locale][post.authorship]}</p>}
            {contentSlots.copyright ? <MarkdownSlot block={contentSlots.copyright} /> : license && <p className="reading-license">{post.licenseUrl ? <a href={post.licenseUrl} target="_blank" rel="noopener noreferrer">{license}</a> : license}</p>}
            <a className="reading-permalink" href={permalink}><Icon name="link" width="15" height="15" />{permalink}</a>
          </div>
        </footer>
      </article>
      {neighbors.length > 0 && (
        <nav className="reading-neighbors" aria-label={{ zh: "相邻文章", en: "Adjacent posts", ja: "前後の記事" }[locale]}>
          {neighbors.map(({ post: item, label }) => (
            <Link key={item.slug} href={localePath(`/posts/${item.slug}`, locale)}>
              <span>{label}</span>
              <strong>{item.title}</strong>
              <Icon name="arrow" width="18" height="18" />
            </Link>
          ))}
        </nav>
      )}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(structuredData).replace(/</g, "\\u003c"),
        }}
      />
    </>
  );
}
